let lname = 'rahim';
console.log(lname == 'rahim');
let fname = "hamza";
console.log(fname != 'hamza');
let _name = "Khan";
console.log(_name == 'khan');
let num1 = 5;
console.log(num1 == 5);
console.log(num1 != 5);
console.log(num1 > 4);
console.log(num1 < 5);
console.log(num1 >= 5);
console.log(num1 <= 3);
let percentage = 60;
console.log(percentage == 60 && percentage > 50);
console.log(percentage == 40 || percentage > 70);
let array = [2,4,6,8,10];
console.log(array[0] == 2);
console.log(array[4] == 8);