let places = ["Makkah","Madina","Turkey","Australia","Switzerland"];
console.log(places);
console.log(places.slice().sort());
console.log(places);
console.log(places.slice().sort().reverse());
console.log(places);
console.log(places.reverse());
console.log(places.reverse());
console.log(places.sort());
console.log(places.reverse());
